services:
  db:
    image: 586794487489.dkr.ecr.us-east-1.amazonaws.com/connecther/db:latest_v2
    # image: data_store:latest
    ports: 
      - "5431:5432"
    # networks:
    #   - back-end

    environment:
      POSTGRES_USER: app_user1  # Set the PostgreSQL user
      POSTGRES_PASSWORD: DeusVult%21  # Set the PostgreSQL password (IMPORTANT: Use secrets in production!)
      POSTGRES_DB: fem_hope  # Set the initial database name
      # PGDATA: /var/lib/postgresql/data/trial/
