"""Handling Multiple Join Paths v2

Revision ID: 507dedd0aa37
Revises: a4c068867e7e
Create Date: 2024-10-21 14:31:16.835018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '507dedd0aa37'
down_revision: Union[str, None] = 'a4c068867e7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
