worker_processes 1;
user nobody nogroup;
events {
    worker_connections 1024;
}
#upstream portal{
#	server 176.58.126.175
#}

http {
server {
    if ($host = lifeportal.kenyanalliance.co.ke) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


	listen 80;
	listen [::]:80;
	server_name lifeportal.kenyanalliance.co.ke;
    return 404; # managed by Certbot


}

server {
	server_name lifeportal.kenyanalliance.co.ke;
#	access_log /var/log/nginx/reverse-access.log;
#	error_log /var/log/ngin/reverse-error.log;
	
	location /{
			proxy_pass http://127.0.0.1:5000;
			proxy_set_header Host $host;
                        proxy_set_header X-Real-IP $remote_addr;
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                        proxy_set_header X-Forwarded-Proto $scheme;
		}
	#location ^~ /static/  {
         #     root /home/admin/app/azure/static/;
#	}

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/lifeportal.kenyanalliance.co.ke/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/lifeportal.kenyanalliance.co.ke/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
   
   #Increase Nginx Timeout
    proxy_read_timeout 300;
    proxy_connect_timeout 300;
    proxy_send_timeout 300;

}

}
