-- Booking requests (30-min expiry), provider availability, live_location on provider list,
-- documents readable by authenticated users for provider portfolios, extended submit_provider_application.
-- Run after: supabase_rls_android.sql, supabase_rls_android_ext.sql (get_providers_for_service),
--            supabase_start_conversation_rpc.sql, get_pending_jobs_rpc.sql (jobs/quotes/chats).
--
-- Includes: ALTER users, booking_requests + RLS, RPCs, REPLACE get_providers_for_service,
--           REPLACE submit_provider_application (adds p_working_hours), documents SELECT policy.

-- =============================================================================
-- 1. Users: booking availability + working hours (from provider application)
-- =============================================================================
ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS available_for_booking boolean NOT NULL DEFAULT true;

ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS working_hours text;

COMMENT ON COLUMN public.users.available_for_booking IS 'When false, hidden from get_providers_for_service.';
COMMENT ON COLUMN public.users.working_hours IS 'Free-text hours shown on provider profile.';

-- =============================================================================
-- 2. booking_requests
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.booking_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id integer NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
  provider_id integer NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
  service_id integer NOT NULL REFERENCES public.services (id) ON DELETE RESTRICT,
  proposed_price double precision NOT NULL DEFAULT 0,
  location_text text,
  latitude double precision,
  longitude double precision,
  message text,
  status text NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  quote_id integer REFERENCES public.quotes (id) ON DELETE SET NULL,
  job_id integer REFERENCES public.jobs (id) ON DELETE SET NULL,
  CONSTRAINT booking_requests_status_check CHECK (
    status = ANY (ARRAY['pending','accepted','declined','expired','cancelled']::text[])
  )
);

CREATE INDEX IF NOT EXISTS idx_booking_requests_provider ON public.booking_requests (provider_id);
CREATE INDEX IF NOT EXISTS idx_booking_requests_client ON public.booking_requests (client_id);
CREATE INDEX IF NOT EXISTS idx_booking_requests_pending_expires ON public.booking_requests (expires_at)
  WHERE status = 'pending';

ALTER TABLE public.booking_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "booking_requests_select_parties" ON public.booking_requests;
CREATE POLICY "booking_requests_select_parties" ON public.booking_requests
  FOR SELECT TO authenticated
  USING (client_id = current_user_pk() OR provider_id = current_user_pk());

DROP POLICY IF EXISTS "booking_requests_update_parties" ON public.booking_requests;
CREATE POLICY "booking_requests_update_parties" ON public.booking_requests
  FOR UPDATE TO authenticated
  USING (client_id = current_user_pk() OR provider_id = current_user_pk());

-- =============================================================================
-- 3. Helper: provider has incomplete job (busy)
-- =============================================================================
CREATE OR REPLACE FUNCTION public.provider_has_incomplete_job(p_provider_id integer)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.jobs j
    JOIN public.quotes q ON q.id = j.quote_id
    WHERE q.provider_id = p_provider_id
      AND COALESCE(j.complete, false) = false
  );
$$;

-- =============================================================================
-- 4. Expire stale pending requests (called from list RPC)
-- =============================================================================
CREATE OR REPLACE FUNCTION public.expire_stale_booking_requests()
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  UPDATE public.booking_requests
  SET status = 'expired'
  WHERE status = 'pending' AND expires_at < now();
$$;

GRANT EXECUTE ON FUNCTION public.expire_stale_booking_requests() TO authenticated;
GRANT EXECUTE ON FUNCTION public.expire_stale_booking_requests() TO service_role;

-- =============================================================================
-- 5. create_booking_request
-- =============================================================================
CREATE OR REPLACE FUNCTION public.create_booking_request(
  p_provider_ref text,
  p_service_id integer,
  p_proposed_price double precision,
  p_location_text text DEFAULT NULL,
  p_lat double precision DEFAULT NULL,
  p_lng double precision DEFAULT NULL,
  p_message text DEFAULT NULL
)
RETURNS TABLE (request_id bigint, err text)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_client int;
  v_provider int;
  v_new_id bigint;
BEGIN
  PERFORM public.expire_stale_booking_requests();

  v_client := current_user_pk();
  IF v_client IS NULL THEN
    RETURN QUERY SELECT NULL::bigint, 'not_authenticated'::text;
    RETURN;
  END IF;

  SELECT u.id INTO v_provider
  FROM public.users u
  WHERE u.service_provider = true
    AND COALESCE(u.available_for_booking, true) = true
    AND (u.user_id = p_provider_ref OR u.id::text = p_provider_ref)
  LIMIT 1;

  IF v_provider IS NULL THEN
    RETURN QUERY SELECT NULL::bigint, 'provider_not_found_or_unavailable'::text;
    RETURN;
  END IF;

  IF v_provider = v_client THEN
    RETURN QUERY SELECT NULL::bigint, 'cannot_book_self'::text;
    RETURN;
  END IF;

  IF public.provider_has_incomplete_job(v_provider) THEN
    RETURN QUERY SELECT NULL::bigint, 'provider_busy'::text;
    RETURN;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.subscriptions s
    WHERE s.user_id = v_provider AND s.service_id = p_service_id
  ) THEN
    RETURN QUERY SELECT NULL::bigint, 'provider_not_subscribed_to_service'::text;
    RETURN;
  END IF;

  INSERT INTO public.booking_requests (
    client_id, provider_id, service_id, proposed_price,
    location_text, latitude, longitude, message,
    status, expires_at
  )
  VALUES (
    v_client, v_provider, p_service_id, p_proposed_price,
    NULLIF(trim(p_location_text), ''), p_lat, p_lng, NULLIF(trim(p_message), ''),
    'pending', now() + interval '30 minutes'
  )
  RETURNING id INTO v_new_id;

  RETURN QUERY SELECT v_new_id, NULL::text;
END;
$$;

GRANT EXECUTE ON FUNCTION public.create_booking_request(text, integer, double precision, text, double precision, double precision, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_booking_request(text, integer, double precision, text, double precision, double precision, text) TO service_role;

-- =============================================================================
-- 6. accept_booking_request → quote + chat + job (converted = true)
-- =============================================================================
CREATE OR REPLACE FUNCTION public.accept_booking_request(p_request_id bigint)
RETURNS TABLE (quote_id text, chat_code text, job_id text, err text)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_me int;
  br RECORD;
  v_quote_id int;
  v_chat_code text;
  v_job_id int;
  v_loc text;
  v_geo text := '';
BEGIN
  PERFORM public.expire_stale_booking_requests();

  v_me := current_user_pk();
  IF v_me IS NULL THEN
    RETURN QUERY SELECT NULL::text, NULL::text, NULL::text, 'not_authenticated'::text;
    RETURN;
  END IF;

  SELECT * INTO br FROM public.booking_requests WHERE id = p_request_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN QUERY SELECT NULL::text, NULL::text, NULL::text, 'not_found'::text;
    RETURN;
  END IF;

  IF br.provider_id <> v_me THEN
    RETURN QUERY SELECT NULL::text, NULL::text, NULL::text, 'not_your_request'::text;
    RETURN;
  END IF;

  IF br.status <> 'pending' THEN
    RETURN QUERY SELECT NULL::text, NULL::text, NULL::text, 'not_pending'::text;
    RETURN;
  END IF;

  IF br.expires_at < now() THEN
    UPDATE public.booking_requests SET status = 'expired' WHERE id = p_request_id;
    RETURN QUERY SELECT NULL::text, NULL::text, NULL::text, 'expired'::text;
    RETURN;
  END IF;

  IF public.provider_has_incomplete_job(br.provider_id) THEN
    RETURN QUERY SELECT NULL::text, NULL::text, NULL::text, 'provider_busy'::text;
    RETURN;
  END IF;

  -- Build location: text + optional " · lat,lng"
  IF br.latitude IS NOT NULL AND br.longitude IS NOT NULL THEN
    v_geo := round(br.latitude::numeric, 6)::text || ',' || round(br.longitude::numeric, 6)::text;
  END IF;
  v_loc := NULLIF(trim(COALESCE(br.location_text, '')), '');
  IF v_loc IS NOT NULL AND v_geo <> '' THEN
    v_loc := v_loc || ' · ' || v_geo;
  ELSIF v_loc IS NULL AND v_geo <> '' THEN
    v_loc := v_geo;
  ELSIF v_loc IS NULL THEN
    v_loc := 'Location not specified';
  END IF;

  INSERT INTO public.quotes (client_id, provider_id, service_id, quote_code, converted)
  VALUES (
    br.client_id,
    br.provider_id,
    br.service_id,
    'Q' || substr(md5(random()::text || clock_timestamp()::text), 1, 12),
    true
  )
  RETURNING id INTO v_quote_id;

  v_chat_code := 'CH' || substr(md5(random()::text || clock_timestamp()::text), 1, 14);
  INSERT INTO public.chats (quote_id, chat_code) VALUES (v_quote_id, v_chat_code);

  INSERT INTO public.jobs (quote_id, price, location, date, complete)
  VALUES (
    v_quote_id,
    br.proposed_price,
    v_loc,
    now(),
    false
  )
  RETURNING id INTO v_job_id;

  UPDATE public.booking_requests
  SET status = 'accepted', quote_id = v_quote_id, job_id = v_job_id
  WHERE id = p_request_id;

  RETURN QUERY SELECT v_quote_id::text, v_chat_code, v_job_id::text, NULL::text;
END;
$$;

GRANT EXECUTE ON FUNCTION public.accept_booking_request(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.accept_booking_request(bigint) TO service_role;

-- =============================================================================
-- 7. decline / cancel
-- =============================================================================
CREATE OR REPLACE FUNCTION public.decline_booking_request(p_request_id bigint)
RETURNS TABLE (err text)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_me int;
  br RECORD;
BEGIN
  PERFORM public.expire_stale_booking_requests();
  v_me := current_user_pk();
  IF v_me IS NULL THEN
    RETURN QUERY SELECT 'not_authenticated'::text;
    RETURN;
  END IF;

  SELECT * INTO br FROM public.booking_requests WHERE id = p_request_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN QUERY SELECT 'not_found'::text;
    RETURN;
  END IF;
  IF br.provider_id <> v_me THEN
    RETURN QUERY SELECT 'not_your_request'::text;
    RETURN;
  END IF;
  IF br.status <> 'pending' THEN
    RETURN QUERY SELECT 'not_pending'::text;
    RETURN;
  END IF;

  UPDATE public.booking_requests SET status = 'declined' WHERE id = p_request_id;
  RETURN QUERY SELECT NULL::text;
END;
$$;

GRANT EXECUTE ON FUNCTION public.decline_booking_request(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.decline_booking_request(bigint) TO service_role;

CREATE OR REPLACE FUNCTION public.cancel_booking_request(p_request_id bigint)
RETURNS TABLE (err text)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_me int;
  br RECORD;
BEGIN
  PERFORM public.expire_stale_booking_requests();
  v_me := current_user_pk();
  IF v_me IS NULL THEN
    RETURN QUERY SELECT 'not_authenticated'::text;
    RETURN;
  END IF;

  SELECT * INTO br FROM public.booking_requests WHERE id = p_request_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN QUERY SELECT 'not_found'::text;
    RETURN;
  END IF;
  IF br.client_id <> v_me THEN
    RETURN QUERY SELECT 'not_your_request'::text;
    RETURN;
  END IF;
  IF br.status <> 'pending' THEN
    RETURN QUERY SELECT 'not_pending'::text;
    RETURN;
  END IF;

  UPDATE public.booking_requests SET status = 'cancelled' WHERE id = p_request_id;
  RETURN QUERY SELECT NULL::text;
END;
$$;

GRANT EXECUTE ON FUNCTION public.cancel_booking_request(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.cancel_booking_request(bigint) TO service_role;

-- =============================================================================
-- 8. List my booking requests (JSON rows for mobile)
-- =============================================================================
CREATE OR REPLACE FUNCTION public.get_my_booking_requests()
RETURNS SETOF jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  PERFORM public.expire_stale_booking_requests();
  RETURN QUERY
  SELECT jsonb_build_object(
    'id', b.id,
    'status', b.status,
    'role', CASE WHEN b.client_id = current_user_pk() THEN 'client' ELSE 'provider' END,
    'expires_at', b.expires_at,
    'proposed_price', b.proposed_price,
    'location_text', b.location_text,
    'latitude', b.latitude,
    'longitude', b.longitude,
    'message', b.message,
    'service_id', b.service_id,
    'client_display', COALESCE(c.first_name || ' ' || c.last_name, ''),
    'provider_display', COALESCE(p.first_name || ' ' || p.last_name, ''),
    'created_at', b.created_at
  )
  FROM public.booking_requests b
  JOIN public.users c ON c.id = b.client_id
  JOIN public.users p ON p.id = b.provider_id
  WHERE b.client_id = current_user_pk() OR b.provider_id = current_user_pk()
  ORDER BY b.created_at DESC;
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_my_booking_requests() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_booking_requests() TO service_role;

-- =============================================================================
-- 9. get_providers_for_service: lat/lng, working_hours, exclude busy / unavailable
-- =============================================================================
CREATE OR REPLACE FUNCTION public.get_providers_for_service(p_service_id integer)
RETURNS SETOF jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT jsonb_build_object(
    'first_name', u.first_name,
    'last_name', u.last_name,
    'title', u.title,
    'user_name', u.user_id,
    'phone', u.phone,
    'nat_id', u.nat_id,
    'dob', u.birth_date,
    'gender', u.gender,
    'pic', u.prof_pic,
    'WH Badge', u."WH_badge",
    'area_name', u.area_name,
    'country', u.country,
    'county', u.county,
    'emm_cont_1', u.emm_cont_1,
    'emm_cont_2', u.emm_cont_2,
    'id', u.id,
    'latitude', ll.latitude,
    'longitude', ll.longitude,
    'working_hours', u.working_hours
  )
  FROM public.users u
  JOIN public.subscriptions s ON s.user_id = u.id AND s.service_id = p_service_id
  LEFT JOIN public.live_location ll ON ll.user_id = u.id
  WHERE u.service_provider = true
    AND COALESCE(u.available_for_booking, true) = true
    AND NOT public.provider_has_incomplete_job(u.id);
$$;

GRANT EXECUTE ON FUNCTION public.get_providers_for_service(integer) TO anon;
GRANT EXECUTE ON FUNCTION public.get_providers_for_service(integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_providers_for_service(integer) TO service_role;

-- =============================================================================
-- 10. submit_provider_application — add working_hours (10th param)
-- =============================================================================
CREATE OR REPLACE FUNCTION public.submit_provider_application(
  p_gender text DEFAULT NULL,
  p_birth_date text DEFAULT NULL,
  p_country text DEFAULT NULL,
  p_county text DEFAULT NULL,
  p_area_name text DEFAULT NULL,
  p_nat_id text DEFAULT NULL,
  p_emm_cont_1 text DEFAULT NULL,
  p_emm_cont_2 text DEFAULT NULL,
  p_service_ids text DEFAULT NULL,
  p_working_hours text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_clerk text;
  v_user_pk int;
  v_user_id_str text;
  v_service_ids int[];
BEGIN
  v_clerk := auth.jwt()->>'sub';
  IF v_clerk IS NULL OR v_clerk = '' THEN RETURN; END IF;

  SELECT id, user_id INTO v_user_pk, v_user_id_str
  FROM users WHERE clerk_user_id = v_clerk LIMIT 1;

  IF v_user_pk IS NULL THEN RETURN; END IF;

  IF p_service_ids IS NOT NULL AND trim(p_service_ids) != '' THEN
    BEGIN
      IF p_service_ids ~ '^\[.*\]$' THEN
        SELECT array_agg(elem::int) INTO v_service_ids
        FROM json_array_elements_text(p_service_ids::json) AS elem;
      ELSE
        SELECT array_agg(x::int) INTO v_service_ids
        FROM unnest(string_to_array(trim(p_service_ids), ',')) AS x
        WHERE x ~ '^\s*\d+\s*$';
      END IF;
    EXCEPTION WHEN OTHERS THEN
      v_service_ids := '{}';
    END;
  END IF;

  UPDATE users SET
    gender = NULLIF(trim(p_gender), ''),
    birth_date = CASE WHEN NULLIF(trim(p_birth_date), '') IS NOT NULL AND NULLIF(trim(p_birth_date), '') ~ '^\d{4}-\d{2}-\d{2}$'
      THEN (NULLIF(trim(p_birth_date), ''))::date ELSE birth_date END,
    country = NULLIF(trim(p_country), ''),
    county = NULLIF(trim(p_county), ''),
    area_name = NULLIF(trim(p_area_name), ''),
    nat_id = NULLIF(trim(p_nat_id), ''),
    emm_cont_1 = NULLIF(trim(p_emm_cont_1), ''),
    emm_cont_2 = NULLIF(trim(p_emm_cont_2), ''),
    working_hours = NULLIF(trim(p_working_hours), ''),
    provider_application_pending = true
  WHERE clerk_user_id = v_clerk;

  INSERT INTO provider_applications (user_id, clerk_user_id, user_id_str, status, service_ids, application_data)
  VALUES (
    v_user_pk,
    v_clerk,
    v_user_id_str,
    'pending',
    COALESCE(v_service_ids, '{}'),
    jsonb_build_object(
      'gender', NULLIF(trim(p_gender), ''),
      'birth_date', NULLIF(trim(p_birth_date), ''),
      'country', NULLIF(trim(p_country), ''),
      'county', NULLIF(trim(p_county), ''),
      'area_name', NULLIF(trim(p_area_name), ''),
      'nat_id', NULLIF(trim(p_nat_id), ''),
      'emm_cont_1', NULLIF(trim(p_emm_cont_1), ''),
      'emm_cont_2', NULLIF(trim(p_emm_cont_2), ''),
      'working_hours', NULLIF(trim(p_working_hours), '')
    )
  );
END;
$$;

-- Replace grants for new signature (drop old 9-arg overload if present)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public'
      AND p.proname = 'submit_provider_application'
      AND pg_get_function_identity_arguments(p.oid) = 'text, text, text, text, text, text, text, text, text'
  ) THEN
    EXECUTE 'DROP FUNCTION public.submit_provider_application(text, text, text, text, text, text, text, text, text)';
  END IF;
END $$;

GRANT EXECUTE ON FUNCTION public.submit_provider_application(text, text, text, text, text, text, text, text, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.submit_provider_application(text, text, text, text, text, text, text, text, text, text) TO service_role;

-- =============================================================================
-- 11. Documents: seekers can read rows for service providers (portfolio / KYC display)
-- =============================================================================
DROP POLICY IF EXISTS "documents_seeker_read_portfolio" ON public.documents;
CREATE POLICY "documents_seeker_read_portfolio" ON public.documents
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.users u
      WHERE u.id = documents.user_id AND u.service_provider IS TRUE
    )
  );
